
runtime: python310

instance_class: F2

env_variables:
  FLASK_ENV: production
  FLASK_DEBUG: "false"
  DATABASE_URL: postgresql://username:password@host:port/database
  NEON_DATABASE_URL: postgresql://username:password@host:port/database
  SECRET_KEY: your_production_secret_key_here
  SESSION_SECRET: your_session_secret_here
  WTF_CSRF_SECRET_KEY: your_csrf_secret_key_here
  REDIS_URL: redis://localhost:6379/0
  PGSSLMODE: require
  DATABASE_SSL_MODE: require

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

vpc_access_connector:
  name: projects/PROJECT_ID/locations/REGION/connectors/CONNECTOR_NAME

cloud_sql_instances:
  - INSTANCE_CONNECTION_NAME
