
runtime: python312

instance_class: F2

env_variables:
  FLASK_ENV: production
  FLASK_DEBUG: "false"
  SECRET_KEY: your_production_secret_key_here
  WTF_CSRF_SECRET_KEY: your_csrf_secret_key_here
  NEON_DATABASE_URL: postgresql://username:password@host:port/database
  DATABASE_URL: postgresql://username:password@host:port/database
  REDIS_URL: redis://localhost:6379/0
  PGSSLMODE: require
  DATABASE_SSL_MODE: require
  PORT: 8080

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
- url: /static
  static_dir: static
  secure: always
  expiration: 1h

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  secure: always

- url: /.*
  script: auto
  secure: always

network:
  session_affinity: true

health_check:
  enable_health_check: true
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2

liveness_check:
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
