runtime: python310

entrypoint: gunicorn -b :8080 app:app  

env_variables:
  FLASK_ENV: production
  DATABASE_URL: sqlite:///accufin360.db
  SECRET_KEY: your_secret_key_here
  SESSION_SECRET: your_session_secret_here



