version: '3.8'

services:
  # F-AI Accountant Application
  fai-accountant:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://fai_user:fai_password@postgres:5432/fai_accountant
      - SECRET_KEY=fai-accountant-docker-secret-2024
      - SESSION_SECRET=fai-session-docker-secret-2024
      - FLASK_ENV=production
    depends_on:
      - postgres
      - redis
    volumes:
      - ./uploads:/app/uploads
      - ./reports:/app/reports
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - fai-network

  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=fai_accountant
      - POSTGRES_USER=fai_user
      - POSTGRES_PASSWORD=fai_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - fai-network

  # Redis for Session Management
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - fai-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - fai-accountant
    restart: unless-stopped
    networks:
      - fai-network

volumes:
  postgres_data:
  redis_data:

networks:
  fai-network:
    driver: bridge